### ISSUE TITLE
Snellen VA

### ISSUE THREAD

**Issue by ayl** [tjebo/eye#1]
I reviewed the code and I am not sure that this code will handle the +/- letters when converting from Snellen to logMAR or ETDRS.

**Comment by tjebo** [comment]
@ayl 
This is a great feedback, and I appreciate that you took the time to look into the code. I am also impressed that you spotted this flaw so quickly. 

I agree this is an issue - the current design simply removes the entries after the first occurring plus/minus, thus ignoring them. I believe that it will reflect the "actual" measurement in many, but unfortunately not all cases, in very particular when dealing with "minus" entries. 

Both entries of "20/50+3" and  "20/50-3" thus will be interpreted as 20/50, but the latter should ideally be a line lower. 

Plus/minus entries seem fundamentally flawed to me, because using those entries fail to follow the intricate design of the tests which aim to provide a single value to "visual acuity".  Unfortunately, I don't find it easy to deal with the problem, mostly because of the different chart designs (Different "line steps" and different numbers of optotypes in lines). 

However, they are used, and they are also entered into electronic medical records. So my decision was to keep it simple and accept the flaw that conversion might not always be ideal in some cases. 

I think it would make sense to make a conditional transformation, e.g. like this:
-1 to +3 : take same Snellen value
<= -2 : take Snellen value one line below
>+3 (unlikely entries, but unfortunately not impossible) Snellen value one line above

Would you think that seems reasonable?

**Comment by tjebo** [comment]
also cf the updated readme https://github.com/tjebo/eye/#va

**Comment by ayl** [comment]
@tjebo Take a look at this code repo https://github.com/ayl/vaextractor. I tried to resolve this by assuming 5 letters per line and the standard lines on most snellen charts.

**Comment by tjebo** [comment]
This is very interesting, thank you and I see what you mean. 

However,  I am not sure I would want to follow this approach, considering the design of Snellen charts and assignment of values based on non-arbitrary psychometric thresholds. They are not meant to have "values in between". 
I may, however, leave this decision to the researcher and include an option to evaluate the plus/minus entries to logmar .

**Comment by tjebo** [comment]
@ayl have added such an option now. It converts to the closest snellen line by default, but also allows the researcher to evaluate plus/minus entries as logmar/etdrs

**Comment by ayl** [comment]
Cool!
